apiVersion: v1
kind: Pod
metadata:
  name: pod-inspector
spec:
  containers:
    - name: pod-inspector
      image: b.gcr.io/kuar/pod-inspector
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  restartPolicy: Always
